#! /bin/sh

source my_functions
source my_variables

my_requirements 'bspc' || exit 1

bspc monitor -d 1 2 3 4 5 6 7 8 9 0  

bspc config border_width			"$my_border_size"
bspc config window_gap				"$my_padding_size"
bspc config normal_border_color		"$my_active_bg"
bspc config focused_border_color	"$my_active_fg"

bspc config top_padding				0
bspc config right_padding			0
bspc config bottom_padding			0
bspc config left_padding			0

bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config pointer_modifier		mod1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-appfinder state=floating
