#!/bin/bash

source my_functions
source my_variables

my_requirements 'sxhkd' || exit

config=$(my_config_for 'keybindings')

cat > "$config" <<EOF

#						  GENERAL KEYBINDINGS

# Reload sxhkd config
alt + F1
	pgrep sxhkd | xargs kill -s 10 | notify-send "Just reloaded sxhkd"

# Open application finder collapsed
alt + g; r
	my_dmenu_run

# Change my current theme
alt + g; t
	my_themes

alt + g; p 
	scrot -s -f - | xclip -selection clipboard -t image/png -i 


#								 VOLUME CONTROL

# Toggle mute
XF86AudioMute
	amixer -q -D pulse set Master 1+ toggle

# Raise volume
XF86AudioRaiseVolume
	amixer -q set Master 5%+

# Lower volume
XF86AudioLowerVolume
	amixer -q set Master 5%-


#							   BSPWM KEYBINDINGS 

# Focus the node do the specified direction
alt + {h,j,k,l}
	bspc node -f {west, south, north, east}.leaf

# Move the node to the specified direction
alt + shift + {h,j,k,l}
	bspc node -s {west, south, north, east}.leaf --follow


# Focus the next or previous node
alt + {n,p}
	bspc node -f {next,prev}.leaf

# Swap with the next or previous node 
alt + shift + {n,p}
	bspc node -s {next,prev}.leaf  --follow

# Focus the specified desktop
alt + {0-9}
	bspc desktop -f {0-9}

# Send the focused node to the specified desktop
alt + shift + {1-9}
	bspc node -d {1-9} --follow

alt + shift + c
	bspc node --close

# restart 
alt + w; r
	bspc wm -r

# quit
alt + w; q
	bspc quit

#Move, Change, Resize, Swap, Send

EOF

if pgrep sxhkd > /dev/null
then
	pgrep sxhkd | xargs kill -s 10
else
	pgrep sxhkd > /dev/null || sxhkd -c "$config" &
fi
