#!/bin/bash

source my_functions
source my_variables

my_requirements 'sxhkd' || exit 1

config=$(my_config_for 'keybindings')
prefix="alt + b"

cat > "$config" <<EOF

# Reload sxhkd config
$prefix; shift + R
	pgrep sxhkd | xargs kill -s 10 | notify-send "Just reloaded sxhkd"
# Run application
$prefix; shift + S
	systemctl suspend

# Run application
$prefix; r
	my_dmenu_run

# Change window name
$prefix; shift + a 
	my_window_name

# Change theme
$prefix; shift + t
	my_themes

# Print screen region
$prefix; shift + p
	scrot -s -f - | xclip -selection clipboard -t image/png -i

# Launch terminal
$prefix; t
	my_terminal

# Focus the node do the specified direction
$prefix; {h,j,k,l}
	bspc node -f {west, south, north, east}.leaf

# Move the node to the specified direction
$prefix; shift + {h,j,k,l}
	bspc node -s {west, south, north, east}.leaf --follow

	# Focus the next or previous node
$prefix; {n,p}
	bspc node -f {next,prev}.local.leaf

# Swap with the next or previous node
$prefix; shift + {n,p}
	bspc node -s {next,prev}.local.leaf --follow

# Focus the specified desktop
$prefix; {0-9}
	bspc desktop -f {0-9}

# Toggle layouts
$prefix; m
	bspc desktop -l next

# Send the focused node to the specified desktop
$prefix; shift + {1-9}
	bspc node -d {1-9} --follow

$prefix; shift + c
	bspc node --close

$prefix; + shift + q
	bspc quit

# Toggle mute
XF86AudioMute
	amixer -q -D pulse set Master 1+ toggle

# Raise volume
XF86AudioRaiseVolume
	amixer -q set Master 5%+

# Lower volume
XF86AudioLowerVolume
	amixer -q set Master 5%-

EOF

pkill -10 -x sxhkd || sxhkd -c "$config" &
