#!/bin/bash 

source my_functions
source my_variables

my_requirements 'tmux' || exit 1

config=$(my_config_for 'tmux')

cat > "$config" <<EOF

set-option -g base-index 1
set-option -g status-style bg=$my_active_bg,fg=$my_active_fg
set-option -g pane-border-indicators off
set-option -g pane-active-border-style fg=$my_active_fg
set-option -g pane-border-style fg=$my_inactive_fg

set-option -g status-right '%H:%M'

set-option -ga terminal-overrides "xterm-256color:Tc"

set-option -g mode-keys vi
set-option -g status-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key H resize-pane -L 5
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key L resize-pane -R 5

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

bind-key r source-file $config

EOF

test "$TERM" = tmux-256color && exit

tmux -T RGB -f "$config"
