#!/bin/bash

source ~/.cache/wal/colors.sh

white='#ffffff'
black='#000000'

my_font='Terminus (TTF)'
my_font_size=12
my_active_bg=${background:-$black}
my_active_fg=${color4:-$white}
my_inactive_bg=${background:-$white}
my_inactive_fg=${foreground:-$black}
my_border_size=1
my_padding_size=4
