#!/bin/bash

source my_functions
source my_variables

my_requirements 'my_dmenu' 'xdotool' || exit 1

name=$(my_dmenu -p "New window name:" < /dev/null)

test $? -eq 0 && xdotool getwindowfocus set_window --name "$name"
